//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndoorMappingApp.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IndoorMappingApp.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string AccountSettings_ChangePassword {
            get {
                return ResourceManager.GetString("AccountSettings_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Account Settings.
        /// </summary>
        internal static string AccountSettings_Title {
            get {
                return ResourceManager.GetString("AccountSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Available Routes.
        /// </summary>
        internal static string Button_AvailableRoutes {
            get {
                return ResourceManager.GetString("Button_AvailableRoutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        internal static string Button_ChangePassword {
            get {
                return ResourceManager.GetString("Button_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B304.
        /// </summary>
        internal static string Button_Dest_B304 {
            get {
                return ResourceManager.GetString("Button_Dest_B304", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B404.
        /// </summary>
        internal static string Button_Dest_B404 {
            get {
                return ResourceManager.GetString("Button_Dest_B404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        internal static string Button_Enter {
            get {
                return ResourceManager.GetString("Button_Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        internal static string Button_ForgotPassword {
            get {
                return ResourceManager.GetString("Button_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Button_Options {
            get {
                return ResourceManager.GetString("Button_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Button_Register {
            get {
                return ResourceManager.GetString("Button_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        internal static string Button_SaveChanges {
            get {
                return ResourceManager.GetString("Button_SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Send Feedback.
        /// </summary>
        internal static string Button_SendFeedback {
            get {
                return ResourceManager.GetString("Button_SendFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose at least one option..
        /// </summary>
        internal static string ChooseOneOption {
            get {
                return ResourceManager.GetString("ChooseOneOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISEP E-mail.
        /// </summary>
        internal static string Entry_Email_Placeholder {
            get {
                return ResourceManager.GetString("Entry_Email_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ***********.
        /// </summary>
        internal static string Entry_NewPassword_Placeholder {
            get {
                return ResourceManager.GetString("Entry_NewPassword_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        internal static string Entry_Password_Placeholder {
            get {
                return ResourceManager.GetString("Entry_Password_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        internal static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback Options.
        /// </summary>
        internal static string FeedbackOptions_Title {
            get {
                return ResourceManager.GetString("FeedbackOptions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback Summited.
        /// </summary>
        internal static string FeedbackSubmitted {
            get {
                return ResourceManager.GetString("FeedbackSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        internal static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a destination:.
        /// </summary>
        internal static string Label_ChooseDestination {
            get {
                return ResourceManager.GetString("Label_ChooseDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Confirm Password.
        /// </summary>
        internal static string Label_ConfirmPassword {
            get {
                return ResourceManager.GetString("Label_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Don’t have an account?.
        /// </summary>
        internal static string Label_DontHaveAccount {
            get {
                return ResourceManager.GetString("Label_DontHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISEP Number.
        /// </summary>
        internal static string Label_IsepNumber {
            get {
                return ResourceManager.GetString("Label_IsepNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISEP Number.
        /// </summary>
        internal static string Label_IsepNumber_Feedback {
            get {
                return ResourceManager.GetString("Label_IsepNumber_Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Label_Language {
            get {
                return ResourceManager.GetString("Label_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Project Logo.
        /// </summary>
        internal static string Label_LogoText {
            get {
                return ResourceManager.GetString("Label_LogoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  New Password.
        /// </summary>
        internal static string Label_NewPassword {
            get {
                return ResourceManager.GetString("Label_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is this message related to any path? Leave empty if not..
        /// </summary>
        internal static string Label_PathRelated {
            get {
                return ResourceManager.GetString("Label_PathRelated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical Limitation.
        /// </summary>
        internal static string Label_PhysicalLimitation {
            get {
                return ResourceManager.GetString("Label_PhysicalLimitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Limitation.
        /// </summary>
        internal static string LimitationPicker {
            get {
                return ResourceManager.GetString("LimitationPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Error!.
        /// </summary>
        internal static string Login_Failure_Title {
            get {
                return ResourceManager.GetString("Login_Failure_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Credentials.
        /// </summary>
        internal static string Login_Invalid_Credentials {
            get {
                return ResourceManager.GetString("Login_Invalid_Credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter both email and password..
        /// </summary>
        internal static string Login_Validation_Error {
            get {
                return ResourceManager.GetString("Login_Validation_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginPage_Label_Login {
            get {
                return ResourceManager.GetString("LoginPage_Label_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginPage_Title {
            get {
                return ResourceManager.GetString("LoginPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been logged out..
        /// </summary>
        internal static string Logout_message {
            get {
                return ResourceManager.GetString("Logout_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (e.g. “Current route…”).
        /// </summary>
        internal static string MainMenuPage_Label_RouteInfo {
            get {
                return ResourceManager.GetString("MainMenuPage_Label_RouteInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Menu.
        /// </summary>
        internal static string MainMenuPage_Title {
            get {
                return ResourceManager.GetString("MainMenuPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string MenuPage_Button_LoginPrompt {
            get {
                return ResourceManager.GetString("MenuPage_Button_LoginPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese.
        /// </summary>
        internal static string MenuPage_Button_Portuguese {
            get {
                return ResourceManager.GetString("MenuPage_Button_Portuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string MenuPage_Button_RegisterTitle {
            get {
                return ResourceManager.GetString("MenuPage_Button_RegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try as Guest.
        /// </summary>
        internal static string MenuPage_Button_TryAsGuest {
            get {
                return ResourceManager.GetString("MenuPage_Button_TryAsGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Reminder Notification.
        /// </summary>
        internal static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option 1.
        /// </summary>
        internal static string Option1 {
            get {
                return ResourceManager.GetString("Option1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path seems very optimal..
        /// </summary>
        internal static string Option1_Text {
            get {
                return ResourceManager.GetString("Option1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option 2.
        /// </summary>
        internal static string Option2 {
            get {
                return ResourceManager.GetString("Option2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path is always full of people..
        /// </summary>
        internal static string Option2_Text {
            get {
                return ResourceManager.GetString("Option2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option 3.
        /// </summary>
        internal static string Option3 {
            get {
                return ResourceManager.GetString("Option3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app is too slow to work on a daily basis..
        /// </summary>
        internal static string Option3_Text {
            get {
                return ResourceManager.GetString("Option3_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option 4.
        /// </summary>
        internal static string Option4 {
            get {
                return ResourceManager.GetString("Option4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The neurolink is not working properly..
        /// </summary>
        internal static string Option4_Text {
            get {
                return ResourceManager.GetString("Option4_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option 5.
        /// </summary>
        internal static string Option5 {
            get {
                return ResourceManager.GetString("Option5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  My position on the map is inaccurate..
        /// </summary>
        internal static string Option5_Text {
            get {
                return ResourceManager.GetString("Option5_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Settings.
        /// </summary>
        internal static string Options_AccountSettings {
            get {
                return ResourceManager.GetString("Options_AccountSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Account.
        /// </summary>
        internal static string Options_Delete {
            get {
                return ResourceManager.GetString("Options_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give us Feedback.
        /// </summary>
        internal static string Options_GiveUsFeedback {
            get {
                return ResourceManager.GetString("Options_GiveUsFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        internal static string Options_Logout {
            get {
                return ResourceManager.GetString("Options_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path Problems? Share them..
        /// </summary>
        internal static string Options_PathProblems {
            get {
                return ResourceManager.GetString("Options_PathProblems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string OptionsPage_Title {
            get {
                return ResourceManager.GetString("OptionsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paraplegic.
        /// </summary>
        internal static string Paraplegic {
            get {
                return ResourceManager.GetString("Paraplegic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was not possible to obtain a path..
        /// </summary>
        internal static string Path_Message {
            get {
                return ResourceManager.GetString("Path_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send warning.
        /// </summary>
        internal static string PathProblems_Button_SendWarning {
            get {
                return ResourceManager.GetString("PathProblems_Button_SendWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obstruction in the path..
        /// </summary>
        internal static string PathProblems_Checkbox_Obstruction {
            get {
                return ResourceManager.GetString("PathProblems_Checkbox_Obstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other problem..
        /// </summary>
        internal static string PathProblems_Checkbox_OtherProblem {
            get {
                return ResourceManager.GetString("PathProblems_Checkbox_OtherProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISEP Number.
        /// </summary>
        internal static string PathProblems_IsepNumber {
            get {
                return ResourceManager.GetString("PathProblems_IsepNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the option that corresponds to the obstruction..
        /// </summary>
        internal static string PathProblems_ObstructionInstruction {
            get {
                return ResourceManager.GetString("PathProblems_ObstructionInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please tell what’s the other problem.
        /// </summary>
        internal static string PathProblems_OtherProblem_Placeholder {
            get {
                return ResourceManager.GetString("PathProblems_OtherProblem_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Broken Elevator....
        /// </summary>
        internal static string PathProblems_Picker_SelectElevator {
            get {
                return ResourceManager.GetString("PathProblems_Picker_SelectElevator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Path....
        /// </summary>
        internal static string PathProblems_Picker_SelectPath {
            get {
                return ResourceManager.GetString("PathProblems_Picker_SelectPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Logo.
        /// </summary>
        internal static string PathProblems_ProjectLogo {
            get {
                return ResourceManager.GetString("PathProblems_ProjectLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Elevator.
        /// </summary>
        internal static string PathProblems_SelectElevator {
            get {
                return ResourceManager.GetString("PathProblems_SelectElevator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path Problems.
        /// </summary>
        internal static string PathProblems_Title {
            get {
                return ResourceManager.GetString("PathProblems_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What path has the problem?.
        /// </summary>
        internal static string PathProblems_WhatPathQuestion {
            get {
                return ResourceManager.GetString("PathProblems_WhatPathQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string Picker_Language_English {
            get {
                return ResourceManager.GetString("Picker_Language_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese.
        /// </summary>
        internal static string Picker_Language_Portuguese {
            get {
                return ResourceManager.GetString("Picker_Language_Portuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string Picker_Limitation_None {
            get {
                return ResourceManager.GetString("Picker_Limitation_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paraplegic.
        /// </summary>
        internal static string Picker_Limitation_Paraplegic {
            get {
                return ResourceManager.GetString("Picker_Limitation_Paraplegic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quadriplegic.
        /// </summary>
        internal static string Picker_Limitation_Quadriplegic {
            get {
                return ResourceManager.GetString("Picker_Limitation_Quadriplegic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string Picker_Path_No {
            get {
                return ResourceManager.GetString("Picker_Path_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Select your option.
        /// </summary>
        internal static string Picker_Path_Title {
            get {
                return ResourceManager.GetString("Picker_Path_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path x \ Yes.
        /// </summary>
        internal static string Picker_Path_Yes_X {
            get {
                return ResourceManager.GetString("Picker_Path_Yes_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path y \ Yes.
        /// </summary>
        internal static string Picker_Path_Yes_Y {
            get {
                return ResourceManager.GetString("Picker_Path_Yes_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the email associated to your account..
        /// </summary>
        internal static string Recover_Email_Text {
            get {
                return ResourceManager.GetString("Recover_Email_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Login.
        /// </summary>
        internal static string RecoverAccount_Button_BackToLogin {
            get {
                return ResourceManager.GetString("RecoverAccount_Button_BackToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string RecoverAccount_Button_Confirm {
            get {
                return ResourceManager.GetString("RecoverAccount_Button_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Email.
        /// </summary>
        internal static string RecoverAccount_Button_SendEmail {
            get {
                return ResourceManager.GetString("RecoverAccount_Button_SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email provided does not have a registered account..
        /// </summary>
        internal static string RecoverAccount_Label_EnterEmail {
            get {
                return ResourceManager.GetString("RecoverAccount_Label_EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’ve sent you a verification token. Please enter it below..
        /// </summary>
        internal static string RecoverAccount_Label_EnterToken {
            get {
                return ResourceManager.GetString("RecoverAccount_Label_EnterToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A mail will be sent to your email box with instructions to change the password..
        /// </summary>
        internal static string RecoverAccount_Label_Instructions {
            get {
                return ResourceManager.GetString("RecoverAccount_Label_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISEP E-mail.
        /// </summary>
        internal static string RecoverAccount_Placeholder_Email {
            get {
                return ResourceManager.GetString("RecoverAccount_Placeholder_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification token.
        /// </summary>
        internal static string RecoverAccount_Placeholder_Token {
            get {
                return ResourceManager.GetString("RecoverAccount_Placeholder_Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover Account.
        /// </summary>
        internal static string RecoverAccount_Title {
            get {
                return ResourceManager.GetString("RecoverAccount_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        internal static string RecoverPassword_Button_BackToLogin {
            get {
                return ResourceManager.GetString("RecoverPassword_Button_BackToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string RecoverPassword_Button_Change {
            get {
                return ResourceManager.GetString("RecoverPassword_Button_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a New Password.
        /// </summary>
        internal static string RecoverPassword_Label_CreateNew {
            get {
                return ResourceManager.GetString("RecoverPassword_Label_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Recovery.
        /// </summary>
        internal static string RecoverPassword_Label_Header {
            get {
                return ResourceManager.GetString("RecoverPassword_Label_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords match!.
        /// </summary>
        internal static string RecoverPassword_MatchMessage {
            get {
                return ResourceManager.GetString("RecoverPassword_MatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords don’t match!.
        /// </summary>
        internal static string RecoverPassword_MismatchMessage {
            get {
                return ResourceManager.GetString("RecoverPassword_MismatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string RecoverPassword_Placeholder_Confirm {
            get {
                return ResourceManager.GetString("RecoverPassword_Placeholder_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  New Password.
        /// </summary>
        internal static string RecoverPassword_Placeholder_New {
            get {
                return ResourceManager.GetString("RecoverPassword_Placeholder_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Recovery.
        /// </summary>
        internal static string RecoverPassword_Title {
            get {
                return ResourceManager.GetString("RecoverPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account? Login.
        /// </summary>
        internal static string RegisterPage_Button_AlreadyHave {
            get {
                return ResourceManager.GetString("RegisterPage_Button_AlreadyHave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string RegisterPage_Button_Register {
            get {
                return ResourceManager.GetString("RegisterPage_Button_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string RegisterPage_Label_Header {
            get {
                return ResourceManager.GetString("RegisterPage_Label_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string RegisterPage_Limitation_Normal {
            get {
                return ResourceManager.GetString("RegisterPage_Limitation_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paraplegic.
        /// </summary>
        internal static string RegisterPage_Limitation_Paraplegic {
            get {
                return ResourceManager.GetString("RegisterPage_Limitation_Paraplegic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tetraplegic.
        /// </summary>
        internal static string RegisterPage_Limitation_Tetraplegic {
            get {
                return ResourceManager.GetString("RegisterPage_Limitation_Tetraplegic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select physical limitation.
        /// </summary>
        internal static string RegisterPage_Picker_LimitationTitle {
            get {
                return ResourceManager.GetString("RegisterPage_Picker_LimitationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your ISEP E-mail.
        /// </summary>
        internal static string RegisterPage_Placeholder_Email {
            get {
                return ResourceManager.GetString("RegisterPage_Placeholder_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your full name.
        /// </summary>
        internal static string RegisterPage_Placeholder_Name {
            get {
                return ResourceManager.GetString("RegisterPage_Placeholder_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password.
        /// </summary>
        internal static string RegisterPage_Placeholder_Password {
            get {
                return ResourceManager.GetString("RegisterPage_Placeholder_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration failed!.
        /// </summary>
        internal static string Registration_Failure_Message {
            get {
                return ResourceManager.GetString("Registration_Failure_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        internal static string Registration_Failure_Title {
            get {
                return ResourceManager.GetString("Registration_Failure_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration complete!.
        /// </summary>
        internal static string Registration_Success_Message {
            get {
                return ResourceManager.GetString("Registration_Success_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucess!.
        /// </summary>
        internal static string Registration_Success_Title {
            get {
                return ResourceManager.GetString("Registration_Success_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Failure.
        /// </summary>
        internal static string Request_Failed {
            get {
                return ResourceManager.GetString("Request_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        internal static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Failed..
        /// </summary>
        internal static string SettingsFailed {
            get {
                return ResourceManager.GetString("SettingsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings updated successfully..
        /// </summary>
        internal static string SettingsSucess {
            get {
                return ResourceManager.GetString("SettingsSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Room.
        /// </summary>
        internal static string ShowRoom_Label_Header {
            get {
                return ResourceManager.GetString("ShowRoom_Label_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Room 311.
        /// </summary>
        internal static string ShowRoom311 {
            get {
                return ResourceManager.GetString("ShowRoom311", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Room 404.
        /// </summary>
        internal static string ShowRoom404 {
            get {
                return ResourceManager.GetString("ShowRoom404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tetraplegic.
        /// </summary>
        internal static string Tetraplegic {
            get {
                return ResourceManager.GetString("Tetraplegic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not authenticated..
        /// </summary>
        internal static string UserNotAuthenticated {
            get {
                return ResourceManager.GetString("UserNotAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email or recheck its format..
        /// </summary>
        internal static string ValidationError_Email {
            get {
                return ResourceManager.GetString("ValidationError_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter name.
        /// </summary>
        internal static string ValidationError_EnterName {
            get {
                return ResourceManager.GetString("ValidationError_EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Error.
        /// </summary>
        internal static string ValidationError_Title {
            get {
                return ResourceManager.GetString("ValidationError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong token provided. Please provide a valid token.
        /// </summary>
        internal static string ValidationError_Token {
            get {
                return ResourceManager.GetString("ValidationError_Token", resourceCulture);
            }
        }
    }
}
