//------------------------------------------------------------------------------
// <auto-generated>
//     Este código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações a este ficheiro poderão provocar um comportamento incorrecto e perder-se-ão se
//     o código for regenerado.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndoorMappingApp.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IndoorMappingApp.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Change Password.
        /// </summary>
        internal static string AccountSettings_ChangePassword {
            get {
                return ResourceManager.GetString("AccountSettings_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  Account Settings.
        /// </summary>
        internal static string AccountSettings_Title {
            get {
                return ResourceManager.GetString("AccountSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  Available Routes.
        /// </summary>
        internal static string Button_AvailableRoutes {
            get {
                return ResourceManager.GetString("Button_AvailableRoutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Save Changes.
        /// </summary>
        internal static string Button_ChangePassword {
            get {
                return ResourceManager.GetString("Button_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a B304.
        /// </summary>
        internal static string Button_Dest_B304 {
            get {
                return ResourceManager.GetString("Button_Dest_B304", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a B404.
        /// </summary>
        internal static string Button_Dest_B404 {
            get {
                return ResourceManager.GetString("Button_Dest_B404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Enter.
        /// </summary>
        internal static string Button_Enter {
            get {
                return ResourceManager.GetString("Button_Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Forgot Password?.
        /// </summary>
        internal static string Button_ForgotPassword {
            get {
                return ResourceManager.GetString("Button_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ok.
        /// </summary>
        internal static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Options.
        /// </summary>
        internal static string Button_Options {
            get {
                return ResourceManager.GetString("Button_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Register.
        /// </summary>
        internal static string Button_Register {
            get {
                return ResourceManager.GetString("Button_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Save Changes.
        /// </summary>
        internal static string Button_SaveChanges {
            get {
                return ResourceManager.GetString("Button_SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  Send Feedback.
        /// </summary>
        internal static string Button_SendFeedback {
            get {
                return ResourceManager.GetString("Button_SendFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ISEP E-mail.
        /// </summary>
        internal static string Entry_Email_Placeholder {
            get {
                return ResourceManager.GetString("Entry_Email_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ***********.
        /// </summary>
        internal static string Entry_NewPassword_Placeholder {
            get {
                return ResourceManager.GetString("Entry_NewPassword_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Old Password.
        /// </summary>
        internal static string Entry_Password_Placeholder {
            get {
                return ResourceManager.GetString("Entry_Password_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Feedback.
        /// </summary>
        internal static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Feedback Options.
        /// </summary>
        internal static string FeedbackOptions_Title {
            get {
                return ResourceManager.GetString("FeedbackOptions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Feedback Summited.
        /// </summary>
        internal static string FeedbackSubmitted {
            get {
                return ResourceManager.GetString("FeedbackSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Home Page.
        /// </summary>
        internal static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Choose a destination:.
        /// </summary>
        internal static string Label_ChooseDestination {
            get {
                return ResourceManager.GetString("Label_ChooseDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  Confirm Password.
        /// </summary>
        internal static string Label_ConfirmPassword {
            get {
                return ResourceManager.GetString("Label_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  Don’t have an account?.
        /// </summary>
        internal static string Label_DontHaveAccount {
            get {
                return ResourceManager.GetString("Label_DontHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ISEP Number.
        /// </summary>
        internal static string Label_IsepNumber {
            get {
                return ResourceManager.GetString("Label_IsepNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ISEP Number.
        /// </summary>
        internal static string Label_IsepNumber_Feedback {
            get {
                return ResourceManager.GetString("Label_IsepNumber_Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Language.
        /// </summary>
        internal static string Label_Language {
            get {
                return ResourceManager.GetString("Label_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  Project Logo.
        /// </summary>
        internal static string Label_LogoText {
            get {
                return ResourceManager.GetString("Label_LogoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  New Password.
        /// </summary>
        internal static string Label_NewPassword {
            get {
                return ResourceManager.GetString("Label_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Is this message related to any path? Leave empty if not..
        /// </summary>
        internal static string Label_PathRelated {
            get {
                return ResourceManager.GetString("Label_PathRelated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Physical Limitation.
        /// </summary>
        internal static string Label_PhysicalLimitation {
            get {
                return ResourceManager.GetString("Label_PhysicalLimitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Select a Limitation.
        /// </summary>
        internal static string LimitationPicker {
            get {
                return ResourceManager.GetString("LimitationPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Login Error!.
        /// </summary>
        internal static string Login_Failure_Title {
            get {
                return ResourceManager.GetString("Login_Failure_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalid Credentials.
        /// </summary>
        internal static string Login_Invalid_Credentials {
            get {
                return ResourceManager.GetString("Login_Invalid_Credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please enter both email and password..
        /// </summary>
        internal static string Login_Validation_Error {
            get {
                return ResourceManager.GetString("Login_Validation_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Login.
        /// </summary>
        internal static string LoginPage_Label_Login {
            get {
                return ResourceManager.GetString("LoginPage_Label_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Login.
        /// </summary>
        internal static string LoginPage_Title {
            get {
                return ResourceManager.GetString("LoginPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a You have been logged out..
        /// </summary>
        internal static string Logout_message {
            get {
                return ResourceManager.GetString("Logout_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  (e.g. “Current route…”).
        /// </summary>
        internal static string MainMenuPage_Label_RouteInfo {
            get {
                return ResourceManager.GetString("MainMenuPage_Label_RouteInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Main Menu.
        /// </summary>
        internal static string MainMenuPage_Title {
            get {
                return ResourceManager.GetString("MainMenuPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Login.
        /// </summary>
        internal static string MenuPage_Button_LoginPrompt {
            get {
                return ResourceManager.GetString("MenuPage_Button_LoginPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Portuguese.
        /// </summary>
        internal static string MenuPage_Button_Portuguese {
            get {
                return ResourceManager.GetString("MenuPage_Button_Portuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Register.
        /// </summary>
        internal static string MenuPage_Button_RegisterTitle {
            get {
                return ResourceManager.GetString("MenuPage_Button_RegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Try as Guest.
        /// </summary>
        internal static string MenuPage_Button_TryAsGuest {
            get {
                return ResourceManager.GetString("MenuPage_Button_TryAsGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Daily Reminder Notification.
        /// </summary>
        internal static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Option 1.
        /// </summary>
        internal static string Option1 {
            get {
                return ResourceManager.GetString("Option1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The path seems very optimal..
        /// </summary>
        internal static string Option1_Text {
            get {
                return ResourceManager.GetString("Option1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Option 2.
        /// </summary>
        internal static string Option2 {
            get {
                return ResourceManager.GetString("Option2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The path is always full of people..
        /// </summary>
        internal static string Option2_Text {
            get {
                return ResourceManager.GetString("Option2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Option 3.
        /// </summary>
        internal static string Option3 {
            get {
                return ResourceManager.GetString("Option3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a This app is too slow to work on a daily basis..
        /// </summary>
        internal static string Option3_Text {
            get {
                return ResourceManager.GetString("Option3_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Option 4.
        /// </summary>
        internal static string Option4 {
            get {
                return ResourceManager.GetString("Option4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The neurolink is not working properly..
        /// </summary>
        internal static string Option4_Text {
            get {
                return ResourceManager.GetString("Option4_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Option 5.
        /// </summary>
        internal static string Option5 {
            get {
                return ResourceManager.GetString("Option5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  My position on the map is inaccurate..
        /// </summary>
        internal static string Option5_Text {
            get {
                return ResourceManager.GetString("Option5_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Account Settings.
        /// </summary>
        internal static string Options_AccountSettings {
            get {
                return ResourceManager.GetString("Options_AccountSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Give us Feedback.
        /// </summary>
        internal static string Options_GiveUsFeedback {
            get {
                return ResourceManager.GetString("Options_GiveUsFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Log Out.
        /// </summary>
        internal static string Options_Logout {
            get {
                return ResourceManager.GetString("Options_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Path Problems? Share them..
        /// </summary>
        internal static string Options_PathProblems {
            get {
                return ResourceManager.GetString("Options_PathProblems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Options.
        /// </summary>
        internal static string OptionsPage_Title {
            get {
                return ResourceManager.GetString("OptionsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Paraplegic.
        /// </summary>
        internal static string Paraplegic {
            get {
                return ResourceManager.GetString("Paraplegic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a It was not possible to obtain a path..
        /// </summary>
        internal static string Path_Message {
            get {
                return ResourceManager.GetString("Path_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Send warning.
        /// </summary>
        internal static string PathProblems_Button_SendWarning {
            get {
                return ResourceManager.GetString("PathProblems_Button_SendWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Obstruction in the path..
        /// </summary>
        internal static string PathProblems_Checkbox_Obstruction {
            get {
                return ResourceManager.GetString("PathProblems_Checkbox_Obstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Other problem..
        /// </summary>
        internal static string PathProblems_Checkbox_OtherProblem {
            get {
                return ResourceManager.GetString("PathProblems_Checkbox_OtherProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ISEP Number.
        /// </summary>
        internal static string PathProblems_IsepNumber {
            get {
                return ResourceManager.GetString("PathProblems_IsepNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please select the option that corresponds to the obstruction..
        /// </summary>
        internal static string PathProblems_ObstructionInstruction {
            get {
                return ResourceManager.GetString("PathProblems_ObstructionInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please tell what’s the other problem.
        /// </summary>
        internal static string PathProblems_OtherProblem_Placeholder {
            get {
                return ResourceManager.GetString("PathProblems_OtherProblem_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Select Broken Elevator....
        /// </summary>
        internal static string PathProblems_Picker_SelectElevator {
            get {
                return ResourceManager.GetString("PathProblems_Picker_SelectElevator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Select Path....
        /// </summary>
        internal static string PathProblems_Picker_SelectPath {
            get {
                return ResourceManager.GetString("PathProblems_Picker_SelectPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Project Logo.
        /// </summary>
        internal static string PathProblems_ProjectLogo {
            get {
                return ResourceManager.GetString("PathProblems_ProjectLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Select Elevator.
        /// </summary>
        internal static string PathProblems_SelectElevator {
            get {
                return ResourceManager.GetString("PathProblems_SelectElevator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Path Problems.
        /// </summary>
        internal static string PathProblems_Title {
            get {
                return ResourceManager.GetString("PathProblems_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a What path has the problem?.
        /// </summary>
        internal static string PathProblems_WhatPathQuestion {
            get {
                return ResourceManager.GetString("PathProblems_WhatPathQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a English.
        /// </summary>
        internal static string Picker_Language_English {
            get {
                return ResourceManager.GetString("Picker_Language_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Portuguese.
        /// </summary>
        internal static string Picker_Language_Portuguese {
            get {
                return ResourceManager.GetString("Picker_Language_Portuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a None.
        /// </summary>
        internal static string Picker_Limitation_None {
            get {
                return ResourceManager.GetString("Picker_Limitation_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Paraplegic.
        /// </summary>
        internal static string Picker_Limitation_Paraplegic {
            get {
                return ResourceManager.GetString("Picker_Limitation_Paraplegic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Quadriplegic.
        /// </summary>
        internal static string Picker_Limitation_Quadriplegic {
            get {
                return ResourceManager.GetString("Picker_Limitation_Quadriplegic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a No.
        /// </summary>
        internal static string Picker_Path_No {
            get {
                return ResourceManager.GetString("Picker_Path_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  Select your option.
        /// </summary>
        internal static string Picker_Path_Title {
            get {
                return ResourceManager.GetString("Picker_Path_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Path x \ Yes.
        /// </summary>
        internal static string Picker_Path_Yes_X {
            get {
                return ResourceManager.GetString("Picker_Path_Yes_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Path y \ Yes.
        /// </summary>
        internal static string Picker_Path_Yes_Y {
            get {
                return ResourceManager.GetString("Picker_Path_Yes_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please provide the email associated to your account..
        /// </summary>
        internal static string Recover_Email_Text {
            get {
                return ResourceManager.GetString("Recover_Email_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Back to Login.
        /// </summary>
        internal static string RecoverAccount_Button_BackToLogin {
            get {
                return ResourceManager.GetString("RecoverAccount_Button_BackToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Confirm.
        /// </summary>
        internal static string RecoverAccount_Button_Confirm {
            get {
                return ResourceManager.GetString("RecoverAccount_Button_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Send Email.
        /// </summary>
        internal static string RecoverAccount_Button_SendEmail {
            get {
                return ResourceManager.GetString("RecoverAccount_Button_SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The email provided does not have a registered account..
        /// </summary>
        internal static string RecoverAccount_Label_EnterEmail {
            get {
                return ResourceManager.GetString("RecoverAccount_Label_EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a We’ve sent you a verification token. Please enter it below..
        /// </summary>
        internal static string RecoverAccount_Label_EnterToken {
            get {
                return ResourceManager.GetString("RecoverAccount_Label_EnterToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A mail will be sent to your email box with instructions to change the password..
        /// </summary>
        internal static string RecoverAccount_Label_Instructions {
            get {
                return ResourceManager.GetString("RecoverAccount_Label_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ISEP E-mail.
        /// </summary>
        internal static string RecoverAccount_Placeholder_Email {
            get {
                return ResourceManager.GetString("RecoverAccount_Placeholder_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Verification token.
        /// </summary>
        internal static string RecoverAccount_Placeholder_Token {
            get {
                return ResourceManager.GetString("RecoverAccount_Placeholder_Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Recover Account.
        /// </summary>
        internal static string RecoverAccount_Title {
            get {
                return ResourceManager.GetString("RecoverAccount_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Forgot Password?.
        /// </summary>
        internal static string RecoverPassword_Button_BackToLogin {
            get {
                return ResourceManager.GetString("RecoverPassword_Button_BackToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Change Password.
        /// </summary>
        internal static string RecoverPassword_Button_Change {
            get {
                return ResourceManager.GetString("RecoverPassword_Button_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Create a New Password.
        /// </summary>
        internal static string RecoverPassword_Label_CreateNew {
            get {
                return ResourceManager.GetString("RecoverPassword_Label_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Password Recovery.
        /// </summary>
        internal static string RecoverPassword_Label_Header {
            get {
                return ResourceManager.GetString("RecoverPassword_Label_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Passwords match!.
        /// </summary>
        internal static string RecoverPassword_MatchMessage {
            get {
                return ResourceManager.GetString("RecoverPassword_MatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Passwords don’t match!.
        /// </summary>
        internal static string RecoverPassword_MismatchMessage {
            get {
                return ResourceManager.GetString("RecoverPassword_MismatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a New Password.
        /// </summary>
        internal static string RecoverPassword_Placeholder_Confirm {
            get {
                return ResourceManager.GetString("RecoverPassword_Placeholder_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  New Password.
        /// </summary>
        internal static string RecoverPassword_Placeholder_New {
            get {
                return ResourceManager.GetString("RecoverPassword_Placeholder_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Password Recovery.
        /// </summary>
        internal static string RecoverPassword_Title {
            get {
                return ResourceManager.GetString("RecoverPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Already have an account? Login.
        /// </summary>
        internal static string RegisterPage_Button_AlreadyHave {
            get {
                return ResourceManager.GetString("RegisterPage_Button_AlreadyHave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Register.
        /// </summary>
        internal static string RegisterPage_Button_Register {
            get {
                return ResourceManager.GetString("RegisterPage_Button_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Register.
        /// </summary>
        internal static string RegisterPage_Label_Header {
            get {
                return ResourceManager.GetString("RegisterPage_Label_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Normal.
        /// </summary>
        internal static string RegisterPage_Limitation_Normal {
            get {
                return ResourceManager.GetString("RegisterPage_Limitation_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Paraplegic.
        /// </summary>
        internal static string RegisterPage_Limitation_Paraplegic {
            get {
                return ResourceManager.GetString("RegisterPage_Limitation_Paraplegic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tetraplegic.
        /// </summary>
        internal static string RegisterPage_Limitation_Tetraplegic {
            get {
                return ResourceManager.GetString("RegisterPage_Limitation_Tetraplegic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Select physical limitation.
        /// </summary>
        internal static string RegisterPage_Picker_LimitationTitle {
            get {
                return ResourceManager.GetString("RegisterPage_Picker_LimitationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Enter your ISEP E-mail.
        /// </summary>
        internal static string RegisterPage_Placeholder_Email {
            get {
                return ResourceManager.GetString("RegisterPage_Placeholder_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Enter your full name.
        /// </summary>
        internal static string RegisterPage_Placeholder_Name {
            get {
                return ResourceManager.GetString("RegisterPage_Placeholder_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Enter password.
        /// </summary>
        internal static string RegisterPage_Placeholder_Password {
            get {
                return ResourceManager.GetString("RegisterPage_Placeholder_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registration failed!.
        /// </summary>
        internal static string Registration_Failure_Message {
            get {
                return ResourceManager.GetString("Registration_Failure_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error!.
        /// </summary>
        internal static string Registration_Failure_Title {
            get {
                return ResourceManager.GetString("Registration_Failure_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registration complete!.
        /// </summary>
        internal static string Registration_Success_Message {
            get {
                return ResourceManager.GetString("Registration_Success_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sucess!.
        /// </summary>
        internal static string Registration_Success_Title {
            get {
                return ResourceManager.GetString("Registration_Success_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Request Failure.
        /// </summary>
        internal static string Request_Failed {
            get {
                return ResourceManager.GetString("Request_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Select Language.
        /// </summary>
        internal static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Update Failed..
        /// </summary>
        internal static string SettingsFailed {
            get {
                return ResourceManager.GetString("SettingsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Settings updated successfully..
        /// </summary>
        internal static string SettingsSucess {
            get {
                return ResourceManager.GetString("SettingsSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Show Room.
        /// </summary>
        internal static string ShowRoom_Label_Header {
            get {
                return ResourceManager.GetString("ShowRoom_Label_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tetraplegic.
        /// </summary>
        internal static string Tetraplegic {
            get {
                return ResourceManager.GetString("Tetraplegic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please enter your email or recheck its format..
        /// </summary>
        internal static string ValidationError_Email {
            get {
                return ResourceManager.GetString("ValidationError_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Enter name.
        /// </summary>
        internal static string ValidationError_EnterName {
            get {
                return ResourceManager.GetString("ValidationError_EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Validation Error.
        /// </summary>
        internal static string ValidationError_Title {
            get {
                return ResourceManager.GetString("ValidationError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Wrong token provided. Please provide a valid token.
        /// </summary>
        internal static string ValidationError_Token {
            get {
                return ResourceManager.GetString("ValidationError_Token", resourceCulture);
            }
        }
    }
}
